### ISSUE TITLE
Issue in enable_disable toggle button at windows ZitiDesktopEdge app

### ISSUE THREAD

**Issue by vinaynetfoundry** [openziti/desktop-edge-win#100]
[Issue in enable_disable toggle button at windows ZitiDesktopEdge app.zip](https://github.com/openziti/desktop-edge-win/files/5057181/Issue.in.enable_disable.toggle.button.at.windows.ZitiDesktopEdge.app.zip)

**Comment by dovholuknf** [comment]
Thanks for the bug reports @vinaynetfoundry ! We'll take a look and follow up here when it's fixed. The video was really helpful!

**Comment by dovholuknf** [comment]
Issue 1:
if the app has only 1 identity, disabling the one identity does not toggle the "big toggle" button (it probably should)
![image](https://user-images.githubusercontent.com/46322585/89902526-8cbcc880-dbb4-11ea-9aa2-f38dc01e1ec9.png)


Issue 2:
when disabling the identity via the detail card the text on the main screen panel does not say disabled
![image](https://user-images.githubusercontent.com/46322585/89902734-d1486400-dbb4-11ea-8a78-5685f1438535.png)

**Comment by dovholuknf** [comment]
should be fixed with 1.3.0+
