### ISSUE TITLE
installation fails with insufficient privileges

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-win#104]
I clicked to download https://github.com/openziti/desktop-edge-win/releases/download/1.0.5-manual/Ziti.Desktop.Edge-1.0.5.exe in Edge Browser and chose "save" then "run". I accepted the UAC prompt for Ziti Desktop Edge. The prerequisites checker said I needed a tunneler thingy, and I allowed that. Things seemed to progress and now the Ziti Desktop Edge Setup is stuck on "Installing Ziti Desktop Edge..." and I received an error popup about insufficient permissions to start the Ziti Edge system service. I have a screenshot but I'm not sure it would be helpful, and I'm not sure how to attach it in GitHub issues.

**Comment by qrkourier** [comment]
![screenshot](https://i.imgur.com/S29TfEl.png)

**Comment by dovholuknf** [comment]
@JeremyTellier this is the same issue I had with 1.0.4 and that get had. I thought 1.0.5 fixed it for my windows sandbox. I'll have to test it again tomorrow. Is there any better logging we could add? Event viewer wasn't particularly helpful

**Comment by qrkourier** [comment]
I verified the result is the same if I abort the installer process I started with the "run" button after downloading and accepting the UAC, and start over with a right-click -- run as administrator on the downloaded installer .exe.

**Comment by qrkourier** [comment]
The installer succeeded and Desktop Edge is running after a reboot and re-run as administrator of the installer .exe from Downloads.

**Comment by dovholuknf** [comment]
seems like the previous installer left behind some state that forced a reboot. I have successfully installed the 1.0.5 installer in my clean, windows sandbox instance. I'm going to mark this as closed now, reopen if necessary. FYI - you shouldn't need to run as administrator - you _should_ get a UAC prompt if you're not admin.

**Comment by qrkourier** [comment]
![another error during uninstall](https://i.imgur.com/KExYTiF.png)

**Comment by dovholuknf** [comment]
filed https://github.com/openziti/desktop-edge-win/issues/110 to track this
