### ISSUE TITLE
Starting ZitiDesktopEdge app in windows is requesting to start tunnel service

### ISSUE THREAD

**Issue by vinaynetfoundry** [openziti/desktop-edge-win#113]
When I start ZitiDesktopEdge in my windows I am getting a message to start tunnel service.
<img width="290" alt="ZitiDesktopEdge" src="https://user-images.githubusercontent.com/65520423/90769324-a9bc6e80-e30d-11ea-92de-1238dd0ec7ba.png">

**Comment by dovholuknf** [comment]
This is expected behavior if the accompanying service is not started. Can you please look to see if these services are running?
![image](https://user-images.githubusercontent.com/46322585/90769594-7ef6f980-e2be-11ea-9b77-8e15184c72b1.png)

**Comment by dovholuknf** [comment]
If those services are not running - start them. I'm interested in the logs from the Ziti Edge Service as well. The logs are found at 

```
C:\Windows\System32\config\systemprofile\AppData\Roaming\NetFoundry
```

Could you zip the log files in that folder (files starting with ziti-tunneler.log and cziti.log) and attach?

**Comment by vinaynetfoundry** [comment]
The Update service is running but the Edge service is not. I Tried to start but getting error: 
<img width="744" alt="starting service error" src="https://user-images.githubusercontent.com/65520423/90770413-606d1e80-e30f-11ea-99f2-3a1fdbd8cb82.PNG">

I am unable to access the folder C:\Windows\System32\config\ as well.

**Comment by dovholuknf** [comment]
You need to navigate there as administrator. The easiest way to do that is to open `c:\windows\system32` first - then "double click" into the config folder. This will fire a UAC prompt like this 
![image](https://user-images.githubusercontent.com/46322585/90770604-05f8a180-e2c0-11ea-9d02-e4bd3e1e626e.png)

You'll have to do that same process for the `C:\Windows\System32\config\systemprofile` folder as well. But - after that you can just paste the full path into the address bar. 

If the service isn't starting I definitely need to see the logs. Thanks

**Comment by vinaynetfoundry** [comment]
I tried double clicking the folder and it dint display the above UAC prompt. So I navigated to the location from command prompt and took the logs. Please find attached logs.
[NetFoundry.zip](https://github.com/openziti/desktop-edge-win/files/5103067/NetFoundry.zip)

**Comment by dovholuknf** [comment]
Hmmm. The logs look totally clean to me. Can you try this and report the output?
```
c:\programdata\OpenZiti\Service\ziti-tunnel.exe version
[   0.000]    INFO : Logger initialized. Log file located at: C:\Users\User\AppData\Roaming\NetFoundry\ziti-tunneler.log
c:\programdata\OpenZiti\Service\ziti-tunnel.exe version: 0.0.24, revision: 1d9f9fcfbd5b, branch: master, build-by: travis, built-on: 2020-08-18 23:29:49
```

you should be on 0.0.24 of that service

**Comment by vinaynetfoundry** [comment]
ziti-tunnel.exe version throws the below error:
<img width="761" alt="ziti tunnel error" src="https://user-images.githubusercontent.com/65520423/90774522-40405e00-e315-11ea-9ccc-b640249b15e5.PNG">

**Comment by dovholuknf** [comment]
Ah - Thanks Vinay. That's a known (and fixed) issue. Simply uninstall and reinstall the Ziti Desktop Edge for Windows. Cheers
