### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#343]
A small punchlist of UI-related updates that should be made:

* in the (ahem) rare circumstance that the service crashes. Any and all windows that are open that are not the menu or the main form should be closed. This was done recently for the  identity detail page but MFA related form popups should also be cleared. The same is true for when it gets reconnected. Any errors that were shown should be removed/cleared.
* currently if you use up ALL your mfa codes - regenerating them requires you to know to click on the error that is shown if you have none. instead it would be better to pop the recover code page with the error and let the user click 'regenerate' 
![image](https://user-images.githubusercontent.com/46322585/113767742-0d54aa00-96ed-11eb-945d-fa866c3efea5.png)
* whitespace is not clickable in the main window. the red area should all be clickable and bring the detail page up or make it easier to click the 'lock icon' 
![image](https://user-images.githubusercontent.com/46322585/113773537-29a81500-96f4-11eb-85a8-2315b15401e1.png)

**Comment by JeremyTellier** [comment]
Fixes Committed
