### ISSUE TITLE
remove 'old' profiles and unmanaged entries

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#378]
Creating a tun using Wintun seems to leave behind a profile and an 'unmanaged' entry during removal...

Clean them up using:
```
$key="Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Signatures\Unmanaged\*"
Get-ItemProperty -Path $key | where {$_.FirstNetwork -match "ziti.*"} | Remove-Item

$key="Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Profiles\*"
Get-ItemProperty -Path $key | where {$_.ProfileName -match "Ziti.*"} | Remove-Item
```

**Comment by hpfplane** [comment]
Very good for windows 10/11!

**Comment by hpfplane** [comment]
$key="Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Signatures\Unmanaged\*"
Get-ItemProperty -Path $key | where {$_.FirstNetwork -match "网络.*"} | Remove-Item

$key="Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Profiles\*"
Get-ItemProperty -Path $key | where {$_.ProfileName -match "网络.*"} | Remove-Item

**Comment by hpfplane** [comment]
Thank you very much!
