### ISSUE TITLE
Microsoft Defender is flagging the Ziti Desktop Edge installer as unrecognized

### ISSUE THREAD

**Issue by tburtchell** [openziti/desktop-edge-win#416]
Tried installing ziti desktop edge from https://github.com/openziti/desktop-edge-win/releases/tag/1.9.10.  Running the executable triggers the 'Windows protected your PC' screen.   

![image](https://user-images.githubusercontent.com/1058520/126503058-e693e6ec-a6ca-4d38-8ed8-1bb5fe871d01.png)

To install the app:
1. Click "More info"
2. Click "Run anyway"

**Comment by dovholuknf** [comment]
thanks. we changed the way the installer was signed in May 2021. Now the installer is signed by a legitimate, third party but we also sign it using a self-signed certificate which won't be on your local system. Seems like defender is picking up on the fact that this installer has one cert that is not verifiable and flagging it... We did not expect that behavior. 

You can verify / feel good about the install by checking the hash of the file locally. That's easy to do by running 
```
powershell "(Get-FileHash 'Ziti Desktop Edge Client-1.9.10.exe').Hash"
93D218822380C3E8CD639BFD1B27854BC380EE32ED13F2051A71CF7905EEC503
```
that should match the sha256 uploaded for that release: https://github.com/openziti/desktop-edge-win/releases/download/1.9.10/Ziti.Desktop.Edge.Client-1.9.10.exe.sha256

Alternatively look at the executable manually by right clicking on it and going to properties -> Digitial Signatures and inspecting the signatures yourself: 
![image](https://user-images.githubusercontent.com/46322585/126504467-2b7b4d87-f92b-4d39-bad3-ed52880fb274.png)

We'll look at this when we can.

**Comment by dovholuknf** [comment]
We have submitted the exe/installer to MS and they seem to have white listed/fixed whatever they needed to. Can you please uninstall and try again ?
