### ISSUE TITLE
CRASH:  ZDEW crashes changing log levels while the Ziti Desktop Edge service is stopped

### ISSUE THREAD

**Issue by tburtchell** [openziti/desktop-edge-win#462]
To Reproduce:

1. Stop the Ziti Desktop Edge service,  either via the service console or the ZDEW UI
2: Change the log level

Expected behavior:
The log level changes

Observed behavior:
ZDEW crashes

Environment:
Windows Version: Win 10 Pro 21H1
ZDEW Version: 1.10.5.0

Log of the crash:
[ZitiDesktopEdge.log](https://github.com/openziti/desktop-edge-win/files/7322382/ZitiDesktopEdge.log)

**Comment by JeremyTellier** [comment]
This is fixed in the latest commit
