### ISSUE TITLE
Non-disruptive Ziti Desktop Edge Updates

### ISSUE THREAD

**Issue by surennaidu** [openziti/desktop-edge-win#474]
The auto update / installation process in ziti deskop edge is service disruptive where the ziti service and the ongoing connections are terminated as part of the upgrade process.  The user is  therefore forced to lose their application connections or data rather than being able to choose when they wish to update. Can we do our software update like how windows does it - 1. Allow user to manually update 2. Update at set time / after  - ex after x / y/z/ hours that the user can select 3. Allow it to update as per the notification. As orgs start using us for critical apps / traffic, we should handle updates that can be controlled by users such that it doesn't disrupt their work.

**Comment by dovholuknf** [comment]
> Manual update - should be done any time within a week 2. Remind me after x hours, y hours, after 1 day

This will be implemented in the 2.1.4 release (not for the users already deployed).

When a new release is published, after the update check happens (up to 10 minutes), if the UI is open you will see a different icon in the tray showing an update is ready. 

It looks like this:
![image](https://user-images.githubusercontent.com/46322585/180521437-e3a96a9a-04e5-4813-85dc-793e0db739f9.png)

The App then shows the same on the Main Menu:
![image](https://user-images.githubusercontent.com/46322585/180522417-6ccfa4f0-a051-4d0a-a086-8df2e68160fb.png)

Clicking on the Main Menu allows the user to update when they choose. If after 7 days (the default) the user has NOT updated - they will be updated automatically without user interaction 7 days after the publish of the update. If a newer update is published - the clock will reset and the user will have 7 new days.
![image](https://user-images.githubusercontent.com/46322585/180526677-f165db31-4d01-4ba5-8ced-d98463b9a81a.png)

At this time, the user will be continuously nagged that an update is available every 4 hours. If that's too much - we can always tune that down
