### ISSUE TITLE
1.12.x branch does not report app id or app version correctly

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#514]
looking at the json reported - you can see it's wrong:

![image](https://user-images.githubusercontent.com/46322585/156491777-734fd032-0f80-4b89-bd2b-157e7f62303f.png)

I expected to see something like:
![image](https://user-images.githubusercontent.com/46322585/156491962-5ef66b6f-1040-4ec4-af45-416346f00032.png)

**Comment by mary-dcouto** [comment]
Could you please tell me where do I find this json?
