### ISSUE TITLE
UI logs are GIGANTIC on 1.12.x branch

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#515]
![image](https://user-images.githubusercontent.com/46322585/156765567-71fd6699-bb59-49ae-a143-be5327507ff2.png)

these logs should not be gigabytes in size. It appears that this is due to the metrics being pushed to the UI. the metrics op should be fixed. 

after that let's revisit and see if there are more lines that need to be fixed

**Comment by mary-dcouto** [comment]
Raised a PR with the fix in ziti-tunnel-sdk-c repo https://github.com/openziti/ziti-tunnel-sdk-c/pull/306
