### ISSUE TITLE
NUL chars passed to UI via ipc

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#516]
looking at the UI logs I see some NUL chars in notepad++ which should be trimmed/removed/fixed on all IPC ops

![image](https://user-images.githubusercontent.com/46322585/156766784-a692fe0c-9df8-4191-a0f8-7c30451b6cf4.png)

**Comment by mary-dcouto** [comment]
This issue is fixed along with the PR in ziti-tunnel-sdk-c repo https://github.com/openziti/ziti-tunnel-sdk-c/pull/306
