### ISSUE TITLE
crash when waking from sleep and changing networks

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#525]
I put my laptop to sleep last night. I put it in my bag and travelled to a different wifi network. On wake i saw my ZDEW 'off' which is a pretty clear sign the data service crashed.

Crash confirmed by looking at the logs

**Comment by mary-dcouto** [comment]
Could you please share the trace log?

**Comment by dovholuknf** [comment]
Appears to be related to an identity which i had 'forgotten'. I had added an identity yesterday, then i forgot it, then i put the laptop to sleep and moved the network. the crash happened, i just put the laptop to sleep and changed networks and no crash happened.

**Comment by dovholuknf** [comment]
fixed
