### ISSUE TITLE
release-1.12.x - disabled identities are enabled on service restart

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#528]
steps to reproduce:

* install 1.12.x
* disable an identity
* click the 'big off button' in the UI
* click the 'big on button' in the UI
* observe the disabled identity is now enabled

**Comment by larsl-nf** [comment]
[2022-04-08_155340_Lars.zip](https://github.com/openziti/desktop-edge-win/files/8452521/2022-04-08_155340_Lars.zip)
- Logs collected at : 08/04/2022 15:53:34. client version : 1.12.5.0
- Once you disable identities and restart client > identities are active again by default
- 15:53 CET: Tried to add identity Lars-NFSupport-GBG_Enrollment.jwt and get error message
