### ISSUE TITLE
Automatic update did not provide warning period before updating

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#541]
see https://openziti.discourse.group/t/updates-for-zedw/599/4  user was USING ziti via ZDEW when 2.0.0 was published and did not get a warning and could not control when the upgrade happened. this is a poor user experience and we need to at least give them time to close out what they are doing. better yet is to let them delay the update by continually snoozing the update etc

**Comment by gooseleggs** [comment]
This appears to be continuation/similar to #474
