### ISSUE TITLE
Client update management options....

### ISSUE THREAD

**Issue by gooseleggs** [openziti/desktop-edge-win#542]
I was wondering if there would be a a way to control the updates that we are delivering to clients.  Ideally, for windows clients, having a Group Policy would be end goal, but even if the following options could be available in the client.  These options are not just ZEDW related, but maybe across all clients for feature parity.

a) A manual check for updates - something like MAIN MENU > About > Check for Updates - along with a corresponding Yes/No updates available
b) Can we have on the popup that shows update available what version it is updating from and to?
c) Maybe some options to enable/disable auto-update (controlled through Registry - Windows, config file - Linux, preferences file for Mac)
d) Maybe a yes/no button to proceed with update. I was working over ziti connection when it decided to update. We dont want someone working away on something critical (ie remotely applying updates for example), and Ziti decides to force the update as it thinks it is more important than what you are doing

**Comment by gooseleggs** [comment]
Published this, then looked down further, and another user had requested this feature: #474

**Comment by dovholuknf** [comment]
possibly duplicates https://github.com/openziti/desktop-edge-win/issues/417

**Comment by dovholuknf** [comment]
relevant comment from #417: 

> Give notification to the user that update is available and auto install new updates when user stops the ZDE

**Comment by dovholuknf** [comment]
I'm going to close issue since I think it's "mostly complete" (but not exactly as it was written) since it was opened. If there are other changes you'd like to see, please reopen/update the issue or make a new one. Thanks.

**Comment by dovholuknf** [comment]
GPO/registry overrides are coming soon with updates from https://github.com/openziti/desktop-edge-win/issues/985
