### ISSUE TITLE
Upgrade Now always displayed - even when no upgrade exists

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#573]
in 2.1.6+ the 'upgrade now' button shows up even when there is no upgrade

**Comment by dovholuknf** [comment]
![image](https://user-images.githubusercontent.com/46322585/192275451-4affa9f6-f93a-4c44-b7bd-db75ccae7a0f.png)

**Comment by JeremyTellier** [comment]
This was closed in the last release
