### ISSUE TITLE
download/upload speed always 0's

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#618]
at some point, the download/upload speed indicators appear to have stopped for people. I had this issue myself recently, but the 2.1.19 update seemed to fix it for me.  Investigate the issue, add logs to help understand what's happening if needed.

**Comment by Nishantztna** [comment]
Any progress here?

**Comment by dovholuknf** [comment]
The stalled "0" have been fixed, but the values don't seem to be accurate. I'll close this bug as fixed and file a separate one for accuracy
