### ISSUE TITLE
release checksum file not created by sha256sum

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-win#645]
Is there a particular Windows checksum checker the checksum file is intended for? I wasn't able to use it with `sha256sum` because it's not created by `sha256sum`, so it was necessary to manually compare the checksum by opening the file and ignoring the stray characters.

```bash
kbingham@oryp3win10:~$ cd /mnt/c/Users/w/Downloads/

kbingham@oryp3win10:/mnt/c/Users/w/Downloads$ sha256sum --check ./Ziti.Desktop.Edge.Client-2.1.16.exe.sha256
sha256sum: ./Ziti.Desktop.Edge.Client-2.1.16.exe.sha256: no properly formatted SHA256 checksum lines found

kbingham@oryp3win10:/mnt/c/Users/w/Downloads$ cat ./Ziti.Desktop.Edge.Client-2.1.16.exe.sha256
��E4DFE771909B9EBC3B05A98E8F5FDCE2F965DC79199818655EC0270AA3E26248

```

**Comment by dovholuknf** [comment]
my guess is those two files are UTF 32's BOM marker and sha256sum isn't able to process it for 'reasons'. i just checked a recent checksum and can confirm the bom is present.
