### ISSUE TITLE
Support remembering disabled identities on reboot/startup

### ISSUE THREAD

**Issue by tekook** [openziti/desktop-edge-win#681]
Right now every time you restart the client or the tunnel service all identities are enabled by default.
On the iOS App the disabled identities are remembered across app restarts / phone restarts.
This allows to "opt out" of specific identities on demand.

It would be great to have the desktop client behave the same way.
The only issue I found remotely close to this one was: https://github.com/openziti/desktop-edge-win/issues/405, but this describes a bug which I cannot reproduce.

Current behavior:

1. Start desktop client
2. All identities are enabled and will connect
3. Disable one of the identities
4. Restart the client or tunnel
5. Again all identities are enabled and will connected.

Desired behavior:

1. Start desktop client 
2. All identities are enabled and will connect
3. Disable one of the identities
4. Restart the client or tunnel
5. all identities except of the disabled on from step 3. are enabled and will connect

Use case:
I'm using Ziti for my private lab and my work. Would be great to have the work identity only be enabled on the demand and the private one always connected - and vice versa.

Since currently the ZDEW is handling identities system wide, the settings should also be system wide.
In case identities will be handled on user-level, the settings should also be on user-level (as mentioned in https://github.com/openziti/desktop-edge-win/issues/527)

What do you think?

Update: I think https://github.com/openziti/desktop-edge-win/issues/528 reported this as a bug

**Comment by dovholuknf** [comment]
I've apparently not noticed this recently. This is indeed a new bug. The state of the identity SHOULD be remembered. At some point in the past this must have regressed.  We'll take a look. Thanks for reporting it

**Comment by tekook** [comment]
You're very welcome thanks in advance

**Comment by dovholuknf** [comment]
related to https://github.com/openziti/ziti-tunnel-sdk-c/issues/630 and probably https://github.com/openziti/ziti-tunnel-sdk-c/issues/644. I hope to be fixing the dependent bugs and pushing out a release to fix this from our ctrlha alpha stream soon.  It'll still be a minute, but this should make it's way to done in the coming weeks/month ish

**Comment by dovholuknf** [comment]
fixed with 2.5.1
