### ISSUE TITLE
Manual 2.4.0 upgrade not restarting/Stopping UI

### ISSUE THREAD

**Issue by gooseleggs** [openziti/desktop-edge-win#694]
Just installed the 2.4.0 ZDEW client by manually downloading and installing.  It appears to not stop the UI/(services?) during the upgrade.  Therefore when finished, and you *open* the ZDEW it is still showing as the previous version.

![240_upgrade_issue](https://github.com/openziti/desktop-edge-win/assets/9014794/71bb5427-44c8-4673-a065-b66f92fe80df)

I would expect the installer to stop the UI and service prior to installing the new components.

**Comment by dovholuknf** [comment]
It definitely should be doing that. I've seen this happen rarely, but it's not common. The installer software we use IS supposed to close all the components. 

I always test the automatic upgrade functionality and the manual upgrade functionality but if it fails, unfortunately it's never been something we could fix and has always been "something Windows"... 🫤

Does the problem persist if you quit the UI? If it's able to be reproduce we could attempt to get installer logs and I could analyze them and submit them to advanced installer if need be.

**Comment by gooseleggs** [comment]
I sent to be able to reproduce as I did out twice to capture the output. Let me know how to generate the logs and I will see what I can do

**Comment by gooseleggs** [comment]
I have attached installer logs.  Does not terminate the apps at all.   They remain open through out install. 
[MSIDA4C.LOG](https://github.com/user-attachments/files/16093204/MSIDA4C.LOG)

These are some interesting lines:
```
MSI (s) (94:3C) [12:16:15:816]: PROPERTY CHANGE: Adding PrimaryVolumePath property. Its value is 'C:'.
Info 1603. The file C:\Program Files (x86)\NetFoundry Inc\Ziti Desktop Edge\ZitiDesktopEdge.exe is being held in use by the following process: Name: ZitiDesktopEdge, Id: 36552, Window Title: '(not determined yet)'.  Close that application and retry.
Info 1603. The file C:\Program Files (x86)\NetFoundry Inc\Ziti Desktop Edge\ZitiUpdateService.exe is being held in use by the following process: Name: ZitiUpdateService, Id: 19848, Window Title: '(not determined yet)'.  Close that application and retry.
Info 1603. The file C:\Program Files (x86)\NetFoundry Inc\Ziti Desktop Edge\ziti-edge-tunnel.exe is being held in use by the following process: Name: ziti-edge-tunnel, Id: 22536, Window Title: '(not determined yet)'.  Close that application and retry.
MSI (s) (94:3C) [12:17:31:470]: 3 application(s) had been reported to have files in use.
MSI (c) (AC:0C) [12:17:31:476]: File In Use: -ZitiDesktopEdge- Window could not be found. Process ID: 36552
MSI (c) (AC:0C) [12:17:31:477]: File In Use: -ZitiUpdateService- Window could not be found. Process ID: 19848
MSI (c) (AC:0C) [12:17:31:478]: File In Use: -ziti-edge-tunnel- Window could not be found. Process ID: 22536
MSI (c) (AC:0C) [12:17:31:478]: No window with title could be found for FilesInUse
MSI (s) (94:3C) [12:17:31:481]: PROPERTY CHANGE: Modifying PrimaryVolumeSpaceAvailable property. Its current value is '128823808'. Its new value: '128540872'.
MSI (s) (94:3C) [12:17:31:481]: PROPERTY CHANGE: Modifying PrimaryVolumeSpaceRemaining property. Its current value is '128795380'. Its new value: '128512444'.
Action ended 12:17:31: InstallValidate. Return value 1.
```

Not sure if the return value of 1 is good or bad.

**Comment by gooseleggs** [comment]
I installed **Advanced Installer** and started to have a poke around.  Looks fine (from what I have seen), but I wonder if the *Include maximum version in range" needs to be checked as well as per https://www.advancedinstaller.com/forums/viewtopic.php?t=35614.

The *.aip* file from GitHub, is showing 2.3.1 as the *product version*.  This is probably fine as this is a beta and hasn't been submitted to GitHub yet.
![image](https://github.com/openziti/desktop-edge-win/assets/9014794/5c48938a-240e-46c6-b5a5-95b8f91198fd)

The 2.4.0 install file has the correct info on the file (at least in the details section)
![image](https://github.com/openziti/desktop-edge-win/assets/9014794/ed0b9899-7a81-4f98-862f-421ce1e48962)

**Comment by dovholuknf** [comment]
I'm sorry i've lost sight of this. Circling back to it, you have decided to install updates manually instead of using the automatic update facility, correct? What version were you coming from - do you recall? If you reinstalled that older version, does this still happen during upgrade?

As for the .aip difference, that ends up getting set at build time by https://github.com/openziti/desktop-edge-win/blob/release-next/Installer/build.ps1#L89 so the difference in source and release is not uncommon

**Comment by dovholuknf** [comment]
closing for now. if this issue happens again we can open this back up and diagnose
