### ISSUE TITLE
Asking for feedback not allocated enough time to complete

### ISSUE THREAD

**Issue by NicFragale** [openziti/desktop-edge-win#776]
the new build allows for feedback to be collected and zipped - it does complete, however, before the file is zipped the operation claims to have failed.  In the background, the zip completes and can be used.
![image](https://github.com/user-attachments/assets/0280dfb8-da76-4eb8-a1b0-3d8051b8cc41)

**Comment by dovholuknf** [comment]
i can't believe my machine would return feedback in under 3s. thanks for catching this.

**Comment by dovholuknf** [comment]
It might be useful to notice that the task is taking a very long time and then check the log level for the user... users are prone to forgetting how long they've left TRACE on for and that ends up with gigantic logs...  Improving the log collection somehow might be a good idea along with just fixing the 'it didnt work' dialog
