### ISSUE TITLE
document the build process

### ISSUE THREAD

**Issue by dovholuknf** [openziti/desktop-edge-win#79]
new devs/users are left reading Installer\build.ps1 and build.bat to 'figure out' how to build. help them by providing a building.md

**Comment by jkochanik** [comment]
Building the Service is something I want to learn for the Linux Edge. I could make the doc if I could have a quick lesson.

**Comment by jkochanik** [comment]
@dovholuknf

**Comment by mary-dcouto** [comment]
The build process is documented in the building.md file. Hence closing this issue.
