### ISSUE TITLE
Identity Details Height

### ISSUE THREAD

**Issue by JeremyTellier** [openziti/desktop-edge-win#99]
Identity Details Page falls off the bottom when there is not many identities defined

**Comment by dovholuknf** [comment]
closed in 1.3.0 (or thereabouts)

**Comment by dovholuknf** [comment]
if you have many identities, and remove them - this still happens: 
![image](https://user-images.githubusercontent.com/46322585/97877858-cbfa4180-1ceb-11eb-86ad-cedd2978e148.png)

**Comment by dovholuknf** [comment]
closing the app and opening it back up does fix the original issue but - this one remains. here's a pic after stop/start 
![image](https://user-images.githubusercontent.com/46322585/97877980-0368ee00-1cec-11eb-981c-ca3612b74340.png)
